language: node_js
node_js:
  - '0.10'
  - '0.11'
branches:
  except:
  - gh-pages
env:
  global:
    - secure: VvNJOfDRY3RGhng5s01/d7jhrasovFdPZfMsQiN2cc6DZNT1UNiKF6L3SxF4kLEQj9Eqbh6mTV6DTkUAqr17lyY9tXeUvtn1hr1c+GjBxTv9h+0hWcou0XEJaqHf2UrwfP5pWwfs6FyB7NwiGp/mjbVyCjRZutqmg4mcdMYBUdRKpyI1XYTW6L9BsMIwAg2sHxn3beBDu6S3n+2tvD8OqfSVhW0txE9/B5IMWQUo9RjrMQ+NXfGAspja+SUKR8XkP1Qxe8GivX7ad+9vdrXPw0C8yAz/4gNms8iN75eqAISxff/AxQ6mi/boOWRwElYGLSiU+17QYibRnD+5xK98dHj045CHgEQYxL9ucTX3Xm6jBOrNmYOM+egmB9WIu1SmbCmhwdIkHYVsZhwe+LZmTGNJwn2x9mYLc70MZt8wiZWhbnDzAWYK925bk29HPbsaJnQHykliG9tTl6CPorNdhqNgUHEsYsYghJCSYAQBWhK63/+UGK9B+pyqbjeYJnM6EJrg2vEsMSV+rOp4gS1mPkY1/0rXJohbCIta0P/O4lt7HyGxg2tDTnMw9vacIJunrYyv9E91LzUt4jwm4bwfn60PsVNhd3SOBQH1CvDhfzg+EJ+V9WPzOxa2hQ9g/eU8y9ZtDQTh+1dqmt88fQn66DDyzJOR9POTQBV7NRBxe20=
    - secure: nSu7ZSYExaI6WolGM54UVqxf6JNJWxNvi4nriDAg3mQN3P0US+UF6muvhBNvnqUoCquVs6xIx7ZtJo7xuwHRES/9T82OQrulUn952If6Vjq5ktYMqW8K3HRILQhM/Im/cvUwEvOuQQLlknWfHcQ0n4q+oiEQOKeLITDS34PWEejLU9qZ6B4EguUuJUza9yUBsHibck1oqNU14qg9jRTOKk5n0UnfJFjzJtYItJT8uYdZ2eN3zhEgUCVYqal/AmParOUcaJTi1k6eTfvi3OsoYNJWKMjNm0EIltjeJiOeM+DUQp2f03MnNclhg5FtTJRs89uBRB9TfyGgCv74wTrjhaG+OB+9VJ0Yh/oljTa4Q3X44HxKpBYajpekoHoSVyP4NLXaAiNCQO7nzZD5JXXoHp4G0ucvX4XLA0Uh44wvp7RYj/mvjhLTylZCj8JrXDHGTWt6FTQ2Ask8/Kfzvio8qwdohY4RwjlnIVArJOJTLvsz2CRZr+VxUFmYpmSFq0Ky2Oxnwktmeu+pxoKUHrhQ5jydSRUl/URj/2xarpNUqYckR7wqhZ1J9XHgId5xiC770zKQA61g3e25o1rU0V2hpGQG7XdE+P2Ks7chdaahBkDkxZs2c5yhwAlgLoinHCrqcJI56tJWpVGwYqrncB+LmOFLJYpqx5jwzJSiDY3iT58=
addons:
  sauce_connect: true
